version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "8090:8090"
      - "8025:8025"
      - "9323:9323"
    volumes:
      - ./pocketbase/pb_migrations:/leihbase/pocketbase/pb_migrations
      - ./pocketbase/pb_hooks:/leihbase/pocketbase/pb_hooks
      - ./tests/tests:/leihbase/tests/tests
    networks:
      - leihbar

networks:
  leihbar:
