version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_POCKETBASE_SERVER_BASE_URL: http://pocketbase:8090
      NUXT_PUBLIC_POCKETBASE_CLIENT_BASE_URL: http://localhost:8090
      NUXT_PUBLIC_PLAUSIBLE_TRACKING_DOMAIN: ""
      NUXT_PUBLIC_LOCALE: "en"
    networks:
      - leihbar

  pocketbase:
    build:
      context: .
      dockerfile: pocketbase/Dockerfile
      target: prod
      args:
        PORT: 8090
    ports:
      - "8090:8090"
    environment:
      CONFIG_LOCALE: "en"
      # If a reservation needs to have a user, or not
      CONFIG_RESERVATION_REQUIRE_USER: "false"
      CONFIG_LENDING_CONDITIONS_LINK: "https://example.com/lending-conditions"
    networks:
      - leihbar

networks:
  leihbar:
