services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_LOCALE: "${NUXT_PUBLIC_LOCALE:-de}"
      # Pocketbase settings
      NUXT_PUBLIC_POCKETBASE_SERVER_BASE_URL: "${NUXT_PUBLIC_POCKETBASE_SERVER_BASE_URL:-http://pocketbase:8090}"
      NUXT_PUBLIC_POCKETBASE_CLIENT_BASE_URL: "${NUXT_PUBLIC_POCKETBASE_CLIENT_BASE_URL:-http://localhost:8090}"
      # Plausible settings (https://plausible.io/)
      NUXT_PUBLIC_PLAUSIBLE_TRACKING_DOMAIN: "${NUXT_PUBLIC_PLAUSIBLE_TRACKING_DOMAIN:-}"
      # Captcha settings (https://trycap.dev)
      NUXT_PUBLIC_CAP_INSTANCE_HOST: "${NUXT_PUBLIC_CAP_INSTANCE_HOST:-}"
      NUXT_PUBLIC_CAP_SITE_KEY: "${NUXT_PUBLIC_CAP_SITE_KEY:-}"
    networks:
      - leihbar

  pocketbase:
    build:
      context: .
      dockerfile: pocketbase/Dockerfile
      target: prod
      args:
        PORT: 8090
    ports:
      - "8090:8090"
    environment:
      CONFIG_LOCALE: "${CONFIG_LOCALE:-de}"
      # Branding settings (Application name & custom logo: svg, png, jpg, webp)
      CONFIG_APP_NAME: "${CONFIG_APP_NAME:-Leihbase}"
      CONFIG_APP_LOGO: "${CONFIG_APP_LOGO:-}"
      # If a reservation needs to have a user, or not
      CONFIG_RESERVATION_REQUIRE_USER: "${CONFIG_RESERVATION_REQUIRE_USER:-false}"
      CONFIG_LENDING_CONDITIONS_LINK: "${CONFIG_LENDING_CONDITIONS_LINK:-https://example.com/lending-conditions}"
      # Captcha settings (https://trycap.dev)
      CONFIG_CAP_INSTANCE_HOST: "${CONFIG_CAP_INSTANCE_HOST:-}"
      CONFIG_CAP_SITE_KEY: "${CONFIG_CAP_SITE_KEY:-}"
      CONFIG_CAP_SECRET_KEY: "${CONFIG_CAP_SECRET_KEY:-}"
      # Mail / SMTP settings (Email verification, notifications, password reset)
      CONFIG_SMTP_ENABLED: "${CONFIG_SMTP_ENABLED:-false}"
      CONFIG_SMTP_HOST: "${CONFIG_SMTP_HOST:-}"
      CONFIG_SMTP_PORT: "${CONFIG_SMTP_PORT:-587}"
      CONFIG_SMTP_USERNAME: "${CONFIG_SMTP_USERNAME:-}"
      CONFIG_SMTP_PASSWORD: "${CONFIG_SMTP_PASSWORD:-}"
      CONFIG_SMTP_TLS: "${CONFIG_SMTP_TLS:-false}"
      CONFIG_SMTP_AUTH_METHOD: "${CONFIG_SMTP_AUTH_METHOD:-LOGIN}"
      CONFIG_SMTP_SENDER_ADDRESS: "${CONFIG_SMTP_SENDER_ADDRESS:-}"
      CONFIG_SMTP_SENDER_NAME: "${CONFIG_SMTP_SENDER_NAME:-Leihbase}"
      CONFIG_APP_URL: "${CONFIG_APP_URL:-http://localhost:3000}"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_hooks:/pb/pb_hooks
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    networks:
      - leihbar

networks:
  leihbar:
