experimental_monorepo_root = true

[tools]
node = "22.21.0"

[env]
_.source = "./scripts/env.sh"

[tasks.setup]
description = "Setup"
env = { INSTALL_PATH = "{{cwd}}/.bin" }
dir = "{{cwd}}"
file = "https://raw.githubusercontent.com/axllent/mailpit/develop/install.sh"

[tasks.dev]
description = "Run mailpit"
run = "./.bin/mailpit"
