[tasks.dev]
description = "Run app in dev mode"
run = "pnpm run dev"

[tasks.build]
description = "Build app"
run = "pnpm run build"
sources = ["./**/*"]

[tasks.start]
depends = ["build"]
description = "Run app"
run = "pnpm run start"

[tasks.'start:test']
description = "Run test app"
depends = ["build"]
run = "pnpm run start"
[tasks.'start:test'.env]
NUXT_PUBLIC_LOCALE = "en"

[[env]]
NUXT_PUBLIC_POCKETBASE_SERVER_BASE_URL = "http://localhost:8090"
NUXT_PUBLIC_POCKETBASE_CLIENT_BASE_URL = "http://localhost:8090"
NUXT_PUBLIC_PLAUSIBLE_TRACKING_DOMAIN = ""
NUXT_PUBLIC_LOCALE = "en"
NUXT_PUBLIC_CAP_INSTANCE_HOST = ""
NUXT_PUBLIC_CAP_SITE_KEY = ""
[[env]]
_.file = '.env'
